// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: SquareLine_Project

#ifndef UI_SC2_H
#define UI_SC2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_sc2
extern void ui_sc2_screen_init(void);
extern void ui_sc2_screen_destroy(void);
extern lv_obj_t * ui_sc2;
extern lv_obj_t * ui_secondslabel;
extern lv_obj_t * ui_secondslabel2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

