// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_sc2 = NULL;
lv_obj_t * ui_secondslabel = NULL;
lv_obj_t * ui_secondslabel2 = NULL;
// event funtions

// build funtions

void ui_sc2_screen_init(void)
{
    ui_sc2 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_sc2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_sc2, lv_color_hex(0x174F24), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sc2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_secondslabel = lv_label_create(ui_sc2);
    lv_obj_set_width(ui_secondslabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_secondslabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_secondslabel, -71);
    lv_obj_set_y(ui_secondslabel, -5);
    lv_obj_set_align(ui_secondslabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_secondslabel, "sec:");
    lv_obj_set_style_text_color(ui_secondslabel, lv_color_hex(0xC6D1C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_secondslabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_secondslabel, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_secondslabel2 = lv_label_create(ui_sc2);
    lv_obj_set_width(ui_secondslabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_secondslabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_secondslabel2, 85);
    lv_obj_set_y(ui_secondslabel2, -5);
    lv_obj_set_align(ui_secondslabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_secondslabel2, "00");
    lv_obj_set_style_text_color(ui_secondslabel2, lv_color_hex(0xC6D1C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_secondslabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_secondslabel2, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_sc2_screen_destroy(void)
{
    if(ui_sc2) lv_obj_del(ui_sc2);

    // NULL screen variables
    ui_sc2 = NULL;
    ui_secondslabel = NULL;
    ui_secondslabel2 = NULL;

}
