// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_sc1 = NULL;
lv_obj_t * ui_hour = NULL;
lv_obj_t * ui_label = NULL;
lv_obj_t * ui_splitter = NULL;
lv_obj_t * ui_minute = NULL;
lv_obj_t * ui_sign = NULL;
// event funtions

// build funtions

void ui_sc1_screen_init(void)
{
    ui_sc1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_sc1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_sc1, lv_color_hex(0x174F24), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sc1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_hour = lv_label_create(ui_sc1);
    lv_obj_set_width(ui_hour, 95);
    lv_obj_set_height(ui_hour, 90);
    lv_obj_set_x(ui_hour, -70);
    lv_obj_set_y(ui_hour, -4);
    lv_obj_set_align(ui_hour, LV_ALIGN_CENTER);
    lv_label_set_text(ui_hour, "00");
    lv_obj_set_style_text_color(ui_hour, lv_color_hex(0xC6D1C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_hour, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_hour, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label = lv_label_create(ui_sc1);
    lv_obj_set_width(ui_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label, -5);
    lv_obj_set_y(ui_label, -67);
    lv_obj_set_align(ui_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label, "Latest Edtion");

    ui_splitter = lv_label_create(ui_sc1);
    lv_obj_set_width(ui_splitter, 16);
    lv_obj_set_height(ui_splitter, 90);
    lv_obj_set_x(ui_splitter, 6);
    lv_obj_set_y(ui_splitter, -5);
    lv_obj_set_align(ui_splitter, LV_ALIGN_CENTER);
    lv_label_set_text(ui_splitter, ":\n");
    lv_obj_set_style_text_color(ui_splitter, lv_color_hex(0xC6D1C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_splitter, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_splitter, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_minute = lv_label_create(ui_sc1);
    lv_obj_set_width(ui_minute, 95);
    lv_obj_set_height(ui_minute, 90);
    lv_obj_set_x(ui_minute, 88);
    lv_obj_set_y(ui_minute, -5);
    lv_obj_set_align(ui_minute, LV_ALIGN_CENTER);
    lv_label_set_text(ui_minute, "00");
    lv_obj_set_style_text_color(ui_minute, lv_color_hex(0xC6D1C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_minute, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_minute, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sign = lv_label_create(ui_sc1);
    lv_obj_set_width(ui_sign, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sign, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sign, 72);
    lv_obj_set_y(ui_sign, 65);
    lv_obj_set_align(ui_sign, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sign, "Ramiz Mammadli");
    lv_obj_set_style_text_color(ui_sign, lv_color_hex(0xA7B337), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_sign, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_sc1_screen_destroy(void)
{
    if(ui_sc1) lv_obj_del(ui_sc1);

    // NULL screen variables
    ui_sc1 = NULL;
    ui_hour = NULL;
    ui_label = NULL;
    ui_splitter = NULL;
    ui_minute = NULL;
    ui_sign = NULL;

}
